/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TripsCreateRouteImport } from './routes/trips.create'
import { Route as TripsTripidRouteImport } from './routes/trips.$tripid'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppDestinationsRouteImport } from './routes/_app.destinations'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppAccountRouteImport } from './routes/_app.account'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsCreateRoute = TripsCreateRouteImport.update({
  id: '/trips/create',
  path: '/trips/create',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsTripidRoute = TripsTripidRouteImport.update({
  id: '/trips/$tripid',
  path: '/trips/$tripid',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppDestinationsRoute = AppDestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/account': typeof AppAccountRoute
  '/admin': typeof AppAdminRoute
  '/destinations': typeof AppDestinationsRoute
  '/home': typeof AppHomeRoute
  '/trips/$tripid': typeof TripsTripidRoute
  '/trips/create': typeof TripsCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/account': typeof AppAccountRoute
  '/admin': typeof AppAdminRoute
  '/destinations': typeof AppDestinationsRoute
  '/home': typeof AppHomeRoute
  '/trips/$tripid': typeof TripsTripidRoute
  '/trips/create': typeof TripsCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/destinations': typeof AppDestinationsRoute
  '/_app/home': typeof AppHomeRoute
  '/trips/$tripid': typeof TripsTripidRoute
  '/trips/create': typeof TripsCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/signup'
    | '/account'
    | '/admin'
    | '/destinations'
    | '/home'
    | '/trips/$tripid'
    | '/trips/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signup'
    | '/account'
    | '/admin'
    | '/destinations'
    | '/home'
    | '/trips/$tripid'
    | '/trips/create'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/signin'
    | '/signup'
    | '/_app/account'
    | '/_app/admin'
    | '/_app/destinations'
    | '/_app/home'
    | '/trips/$tripid'
    | '/trips/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  TripsTripidRoute: typeof TripsTripidRoute
  TripsCreateRoute: typeof TripsCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/create': {
      id: '/trips/create'
      path: '/trips/create'
      fullPath: '/trips/create'
      preLoaderRoute: typeof TripsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$tripid': {
      id: '/trips/$tripid'
      path: '/trips/$tripid'
      fullPath: '/trips/$tripid'
      preLoaderRoute: typeof TripsTripidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/destinations': {
      id: '/_app/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof AppDestinationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppAdminRoute: typeof AppAdminRoute
  AppDestinationsRoute: typeof AppDestinationsRoute
  AppHomeRoute: typeof AppHomeRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppAdminRoute: AppAdminRoute,
  AppDestinationsRoute: AppDestinationsRoute,
  AppHomeRoute: AppHomeRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  TripsTripidRoute: TripsTripidRoute,
  TripsCreateRoute: TripsCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
