/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TripsTripidRouteImport } from './routes/trips.$tripid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsTripidRoute = TripsTripidRouteImport.update({
  id: '/trips/$tripid',
  path: '/trips/$tripid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/trips/$tripid': typeof TripsTripidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/trips/$tripid': typeof TripsTripidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/trips/$tripid': typeof TripsTripidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/trips/$tripid'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/trips/$tripid'
  id: '__root__' | '/' | '/trips/$tripid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TripsTripidRoute: typeof TripsTripidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$tripid': {
      id: '/trips/$tripid'
      path: '/trips/$tripid'
      fullPath: '/trips/$tripid'
      preLoaderRoute: typeof TripsTripidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TripsTripidRoute: TripsTripidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
