runtime: python39

entrypoint: gunicorn -w 4 -k sanic.worker.GunicornWorker orb:create_app

# Optional: specify an instance class (defaults to F1)
instance_class: F2

# Optional: environment variables
env_variables:
  ENV: "production"

# Optional: automatic scaling settings
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

# Optional: specify network settings
network:
  session_affinity: true
